### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by nagexiaochengzi** [xz-pisces/DGarment#6]
Thanks for your answer, but now “dirt” has error “AttributeError: module ‘dirt’ has no attribute ‘lighting’”, my pytorch version is 1.7.1, does the project have requirements for the torch version?My GPU is a Tesla-V100,any hardware requirements?Is the cuda version 10.1?

**Comment by nagexiaochengzi** [comment]
Could you please explain this to me?

**Comment by xz-pisces** [comment]
from .lighting import *
from tensorflow._api.v2.linalg import cross
normals_by_face /= (tf.norm(normals_by_face, axis=-1, keepdims=True) + 1.e-12)

**Comment by xz-pisces** [comment]
add   "from .lighting import *"  in dirt/__init__.py

**Comment by nagexiaochengzi** [comment]
Thank you. I'll try it right away.
---- Replied Message ----
From ***@***.***> Date 11/13/2024 16:15 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [xz-pisces/DGarment] train error (Issue #6) 
add "from .lighting import *" in dirt/init.py

**Comment by nagexiaochengzi** [comment]
"from tensorflow._api.v2.linalg import cross
normals_by_face /= (tf.norm (normals_by_face, axis=-1, keepdims=True) + 1.e-12)" Where should this sentence be added?

**Comment by nagexiaochengzi** [comment]
Sorry to bother you, there is a new error now。
Training...
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    rendered_normal,mask = renderer.forward(abc)
  File "/home/jkx/projects/mjz/DGarment/render/render_layer.py", line 29, in forward
    camera_t=self.camera_t, camera_rt=self.camera_rt, bgcolor=self.bgcolor,)
  File "/home/jkx/projects/mjz/DGarment/render/render.py", line 53, in render_colored_batch
    vertex_normals_split = dirt.lighting.vertex_normals_pre_split(vertices_split, faces_split)
  File "/home/jkx/anaconda3/envs/dgarment/lib/python3.7/site-packages/dirt-0.3.0-py3.7.egg/dirt/lighting.py", line 120, in vertex_normals_pre_split
    normals_by_face, _ = _get_face_normals(vertices, faces)  # indexed by face-index, *, x/y/z
  File "/home/jkx/anaconda3/envs/dgarment/lib/python3.7/site-packages/dirt-0.3.0-py3.7.egg/dirt/lighting.py", line 29, in _get_face_normals
    normals_by_face = tf.cross(vertices_by_face[:, 1] - vertices_by_face[:, 0], vertices_by_face[:, 2] - vertices_by_face[:, 0])  # indexed by face-index, *, x/y/z
AttributeError: module 'tensorflow' has no attribute 'cross'

**Comment by xusongxuliangwangsulong** [comment]
add  “from tensorflow._api.v2.linalg import cross“  in  /home/jkx/anaconda3/envs/dgarment/lib/python3.7/site-packages/dirt-0.3.0-py3.7.egg/dirt/lighting.py ;  and  modify  "normals_by_face /= （tf.norm （normals_by_face， axis=-1， keepdims=True） + 1.e-12）  " in  _get_face_normals function  of /home/jkx/anaconda3/envs/dgarment/lib/python3.7/site-packages/dirt-0.3.0-py3.7.egg/dirt/lighting.py

**Comment by nagexiaochengzi** [comment]
Thank you for your reply. I modified the corresponding file, but the problem still exists.
